LIST	P=18F452
#INCLUDE	P18F452.INC
ORG		0000H
		GOTO	MAIN
ORG		0030H
MAIN	CLRF	TRISD			;设定D口为输出
		CLRF	PORTD			;RD=00H
		MOVLW	05H				;16位定时方式，64分频
		MOVLW	05H
		MOVWF	T0CON
		BCF		INTCON,TMR0IF	;清标志
		MOVLW	0BH				;初值为0B0CH
		MOVWF	TMR0H			;先赋高0位初值
		MOVLW	0DCH			;后赋低8位初值
		MOVWF	TMR0L
		BSF		T0CON,TMR0ON	;启动TMR0
CHECK	BTFSS	INTCON,TMR0IF	;采用查询的方式等待定时时间
		GOTO	CHECK			;时间未到继续查询
		MOVLW	0BH				;初值重装
		MOVWF	TMR0H			;先赋高8位初值
		MOVLW	0DCH			;后赋低8位初值
		MOVWF	TMR0L
		COMF	PORTD			;翻转引脚电平
		BCF		INTCON,TMR0IF	;清标志
		GOTO	CHECK
		END
